apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.web.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.config.labels | nindent 4 }}
data:
  COMMUNITY_SERVICE: {{ printf "%s:%s" .Values.community.service.name .Values.community.port | quote }}
  IDENTITY_SERVICE: {{ printf "%s:%s" .Values.identity.service.name .Values.identity.port | quote }}
  WORKSHOP_SERVICE: {{ printf "%s:%s" .Values.workshop.service.name .Values.workshop.port | quote }}
  CHATBOT_SERVICE: {{ printf "%s:%s" .Values.chatbot.service.name .Values.chatbot.port | quote }}
  MAILHOG_WEB_SERVICE: {{ printf "%s:%s" .Values.mailhog.webService.name .Values.mailhog.webPort | quote }}
  TLS_ENABLED: {{ .Values.tlsEnabled | quote }}
